### ISSUE TITLE
DXF case weirdness

### ISSUE THREAD

**Issue by ClashTheBunny** [cy384/atreus_bluetooth#1]
I'm getting weirdness with the dxf case.  I did the inkscape part and then opened it up in openscad.  Here is a screenshot of the quarters:
![image](https://user-images.githubusercontent.com/248361/50061404-c205de80-0165-11e9-82cc-24c81c01e2a8.png)

Is there a reason you didn't include a pre-edited dxf in the repo?

**Comment by cy384** [comment]
So the problem /may/ be that you didn't select everything when doing thing in Inkscape, but there are lots of things that could go wrong.  I haven't touched this project in a while, honestly it's a kinda janky solution to getting bluetooth!  I'm going to upload some STLs to Github as a release in a few minutes, hopefully you can just use those if you can't get it working.

Here's a DXF file that works for me.
[case.dxf.zip](https://github.com/cy384/atreus_bluetooth/files/2684277/case.dxf.zip)

**Comment by cy384** [comment]
please let me know if you're still having any issues
